export const REQUESTED_TABLEDATA = 'REQUESTED_TABLEDATA'
export const REQUESTED_TABLEDATA_SUCCEEDED = 'REQUESTED_TABLEDATA_SUCCEEDED'
export const REQUESTED_TABLEDATA_FAILED = 'REQUESTED_TABLEDATA_FAILED'
export const GET_FILTERED_DATA = 'GET_FILTERED_DATA' 


//importing in tableActions.js and tableReducer.js  

